import { defineConfig } from 'vite';

// Migration note: the legacy app serves from /public_html, so the Laravel
// frontend bundle is emitted into public_html/assets/laravel/dist/ (ignored by
// git, regenerated by `npm run build`) where the existing static-file server
// can serve it. The Blade layout references it with
// @assetVersion('/assets/laravel/dist/app.js'). No hashed filenames: the
// asset-version query string (from app_settings) provides cache busting.
export default defineConfig({
    // Laravel's public/ skeleton must not be copied into the build output
    publicDir: false,
    build: {
        outDir: 'public_html/assets/laravel/dist',
        emptyOutDir: true,
        manifest: false,
        rollupOptions: {
            input: 'resources/js/app.js',
            output: {
                entryFileNames: 'app.js',
            },
        },
    },
    server: {
        watch: {
            ignored: ['**/storage/framework/views/**'],
        },
    },
});