import { defineConfig } from 'vite';

// The Laravel frontend bundle is emitted into public/assets/laravel/dist/
// (ignored by git, regenerated by `npm run build`) where Laravel's web server
// can serve it. The Blade layout references it with
// @assetVersion('/assets/laravel/dist/app.js'). No hashed filenames: the
// asset-version query string (from app_settings) provides cache busting.
export default defineConfig({
    // Laravel's public/ skeleton must not be copied into the build output
    publicDir: false,
    build: {
        outDir: 'public/assets/laravel/dist',
        emptyOutDir: true,
        manifest: false,
        rollupOptions: {
            input: 'resources/js/app.js',
            output: {
                entryFileNames: 'app.js',
            },
        },
    },
    server: {
        watch: {
            ignored: ['**/storage/framework/views/**'],
        },
    },
});