-- ========================================
-- টেবিল / Table: autocontent_sources
-- তারিখ / Date: 2026-03-08 02:32:38
-- মোড / Mode: Full Export
-- মোট সারি / Total Rows: 27
-- ========================================

CREATE TABLE IF NOT EXISTS `autocontent_sources` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `url` text NOT NULL,
  `type` enum('rss','html','api','scrape','xml') DEFAULT 'rss',
  `category_id` int(11) DEFAULT NULL,
  `selectors` text DEFAULT NULL,
  `selector_list_container` varchar(500) DEFAULT '',
  `selector_list_item` varchar(500) DEFAULT '',
  `selector_list_title` varchar(500) DEFAULT '',
  `selector_list_link` varchar(500) DEFAULT '',
  `selector_list_date` varchar(500) DEFAULT '',
  `selector_list_image` varchar(500) DEFAULT '',
  `selector_title` varchar(500) DEFAULT '',
  `selector_content` varchar(500) DEFAULT '',
  `selector_image` varchar(500) DEFAULT '',
  `selector_excerpt` varchar(500) DEFAULT '',
  `selector_date` varchar(500) DEFAULT '',
  `selector_author` varchar(500) DEFAULT '',
  `selector_pagination` varchar(500) DEFAULT '',
  `selector_read_more` varchar(500) DEFAULT '',
  `selector_category` varchar(500) DEFAULT '',
  `selector_tags` varchar(500) DEFAULT '',
  `selector_video` varchar(500) DEFAULT '',
  `selector_audio` varchar(500) DEFAULT '',
  `selector_source_url` varchar(500) DEFAULT '',
  `fetch_interval` int(11) DEFAULT 3600,
  `is_active` tinyint(1) DEFAULT 1,
  `last_fetched_at` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  `content_type` enum('articles','pages','mobiles','services') DEFAULT 'articles',
  `scrape_depth` int(11) DEFAULT 1,
  `use_browser` tinyint(1) DEFAULT 0,
  `max_pages` int(11) DEFAULT 50,
  `delay` int(11) DEFAULT 2,
  `selector_list_url` varchar(255) DEFAULT NULL,
  `pagination_type` varchar(50) DEFAULT 'none',
  `pagination_selector` varchar(255) DEFAULT NULL,
  `pagination_pattern` varchar(255) DEFAULT NULL,
  `proxy_enabled` tinyint(1) DEFAULT 0,
  `proxy_provider` varchar(50) DEFAULT NULL,
  `proxy_config` text DEFAULT NULL,
  `last_fetch` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_is_active` (`is_active`),
  KEY `idx_last_fetched` (`last_fetched_at`),
  KEY `category_id` (`category_id`),
  KEY `is_active` (`is_active`),
  KEY `last_fetch` (`last_fetch`)
) ENGINE=InnoDB AUTO_INCREMENT=28 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ডাটা ইনসার্ট / Data Insert

INSERT INTO `autocontent_sources` (`id`, `name`, `url`, `type`, `category_id`, `selectors`, `selector_list_container`, `selector_list_item`, `selector_list_title`, `selector_list_link`, `selector_list_date`, `selector_list_image`, `selector_title`, `selector_content`, `selector_image`, `selector_excerpt`, `selector_date`, `selector_author`, `selector_pagination`, `selector_read_more`, `selector_category`, `selector_tags`, `selector_video`, `selector_audio`, `selector_source_url`, `fetch_interval`, `is_active`, `last_fetched_at`, `created_at`, `content_type`, `scrape_depth`, `use_browser`, `max_pages`, `delay`, `selector_list_url`, `pagination_type`, `pagination_selector`, `pagination_pattern`, `proxy_enabled`, `proxy_provider`, `proxy_config`, `last_fetch`, `updated_at`) VALUES ('1', 'Prothom Alo Latest', 'https://www.prothomalo.com/collection/latest', 'scrape', '1', NULL, '.wide-story-card, .news_with_item', '.news-item', 'h3 a', 'a[href^=\"/story/\"]', '', '', '.story-title h1', '.story-element-text', '.Td4Ec img', '.excerpt-text', 'time[datetime]', '.author-name', '.pagination-next', '', '', '', '', '', '', '1800', '1', NULL, '2026-03-07 18:59:24', 'articles', '1', '0', '50', '2', NULL, 'none', NULL, NULL, '0', NULL, NULL, NULL, '2026-03-07 20:43:27');
INSERT INTO `autocontent_sources` (`id`, `name`, `url`, `type`, `category_id`, `selectors`, `selector_list_container`, `selector_list_item`, `selector_list_title`, `selector_list_link`, `selector_list_date`, `selector_list_image`, `selector_title`, `selector_content`, `selector_image`, `selector_excerpt`, `selector_date`, `selector_author`, `selector_pagination`, `selector_read_more`, `selector_category`, `selector_tags`, `selector_video`, `selector_audio`, `selector_source_url`, `fetch_interval`, `is_active`, `last_fetched_at`, `created_at`, `content_type`, `scrape_depth`, `use_browser`, `max_pages`, `delay`, `selector_list_url`, `pagination_type`, `pagination_selector`, `pagination_pattern`, `proxy_enabled`, `proxy_provider`, `proxy_config`, `last_fetch`, `updated_at`) VALUES ('2', 'BD News 24 Bengali', 'https://bangla.bdnews24.com/', 'scrape', '1', NULL, '.col-md-3', '.SubCat-wrapper', 'h5 a', 'a[href^=\"/\"]', '', '', '.details-title h1', '#contentDetails', '.details-img img', '.short-description', '.publish-time', '.author-name', '.pagination', '', '', '', '', '', '', '1800', '1', NULL, '2026-03-07 18:59:24', 'articles', '1', '0', '50', '2', NULL, 'none', NULL, NULL, '0', NULL, NULL, NULL, '2026-03-07 20:43:27');
INSERT INTO `autocontent_sources` (`id`, `name`, `url`, `type`, `category_id`, `selectors`, `selector_list_container`, `selector_list_item`, `selector_list_title`, `selector_list_link`, `selector_list_date`, `selector_list_image`, `selector_title`, `selector_content`, `selector_image`, `selector_excerpt`, `selector_date`, `selector_author`, `selector_pagination`, `selector_read_more`, `selector_category`, `selector_tags`, `selector_video`, `selector_audio`, `selector_source_url`, `fetch_interval`, `is_active`, `last_fetched_at`, `created_at`, `content_type`, `scrape_depth`, `use_browser`, `max_pages`, `delay`, `selector_list_url`, `pagination_type`, `pagination_selector`, `pagination_pattern`, `proxy_enabled`, `proxy_provider`, `proxy_config`, `last_fetch`, `updated_at`) VALUES ('3', 'BBC Bangla', 'https://www.bbc.com/bengali', 'scrape', '1', NULL, '.bbc-1kr7d6c', '.bbc-1kr7d6c', 'h3 a', 'a[href^=\"/\"]', '', '', 'h1', '.article-body', '.article-hero-image img', '.article-summary', 'time', '.byline', '.pagination', '', '', '', '', '', '', '1800', '1', NULL, '2026-03-07 18:59:24', 'articles', '1', '0', '50', '2', NULL, 'none', NULL, NULL, '0', NULL, NULL, NULL, '2026-03-07 20:43:27');
INSERT INTO `autocontent_sources` (`id`, `name`, `url`, `type`, `category_id`, `selectors`, `selector_list_container`, `selector_list_item`, `selector_list_title`, `selector_list_link`, `selector_list_date`, `selector_list_image`, `selector_title`, `selector_content`, `selector_image`, `selector_excerpt`, `selector_date`, `selector_author`, `selector_pagination`, `selector_read_more`, `selector_category`, `selector_tags`, `selector_video`, `selector_audio`, `selector_source_url`, `fetch_interval`, `is_active`, `last_fetched_at`, `created_at`, `content_type`, `scrape_depth`, `use_browser`, `max_pages`, `delay`, `selector_list_url`, `pagination_type`, `pagination_selector`, `pagination_pattern`, `proxy_enabled`, `proxy_provider`, `proxy_config`, `last_fetch`, `updated_at`) VALUES ('4', 'Daily Star Bangla', 'https://www.thedailystar.net/bangla', 'scrape', '1', NULL, '.view-content', '.views-row', 'h2 a', 'a[href^=\"/bangla\"]', '', '', 'h1', '.field-name-body', '.field-name-field-image img', '.field-name-field-summary', '.date', '.field-author', '.pager', '', '', '', '', '', '', '1800', '1', NULL, '2026-03-07 18:59:24', 'articles', '1', '0', '50', '2', NULL, 'none', NULL, NULL, '0', NULL, NULL, NULL, '2026-03-07 20:43:27');
INSERT INTO `autocontent_sources` (`id`, `name`, `url`, `type`, `category_id`, `selectors`, `selector_list_container`, `selector_list_item`, `selector_list_title`, `selector_list_link`, `selector_list_date`, `selector_list_image`, `selector_title`, `selector_content`, `selector_image`, `selector_excerpt`, `selector_date`, `selector_author`, `selector_pagination`, `selector_read_more`, `selector_category`, `selector_tags`, `selector_video`, `selector_audio`, `selector_source_url`, `fetch_interval`, `is_active`, `last_fetched_at`, `created_at`, `content_type`, `scrape_depth`, `use_browser`, `max_pages`, `delay`, `selector_list_url`, `pagination_type`, `pagination_selector`, `pagination_pattern`, `proxy_enabled`, `proxy_provider`, `proxy_config`, `last_fetch`, `updated_at`) VALUES ('5', 'NTV Bangla', 'https://www.ntvbd.com/bangla', 'scrape', '1', NULL, '.news-list', '.news-item', 'h3 a', 'a[href^=\"/\"]', '', '', 'h1', '.news-details', '.news-image img', '.news-summary', '.news-time', '.reporter-name', '.pagination', '', '', '', '', '', '', '1800', '1', NULL, '2026-03-07 18:59:24', 'articles', '1', '0', '50', '2', NULL, 'none', NULL, NULL, '0', NULL, NULL, NULL, '2026-03-07 20:43:27');
INSERT INTO `autocontent_sources` (`id`, `name`, `url`, `type`, `category_id`, `selectors`, `selector_list_container`, `selector_list_item`, `selector_list_title`, `selector_list_link`, `selector_list_date`, `selector_list_image`, `selector_title`, `selector_content`, `selector_image`, `selector_excerpt`, `selector_date`, `selector_author`, `selector_pagination`, `selector_read_more`, `selector_category`, `selector_tags`, `selector_video`, `selector_audio`, `selector_source_url`, `fetch_interval`, `is_active`, `last_fetched_at`, `created_at`, `content_type`, `scrape_depth`, `use_browser`, `max_pages`, `delay`, `selector_list_url`, `pagination_type`, `pagination_selector`, `pagination_pattern`, `proxy_enabled`, `proxy_provider`, `proxy_config`, `last_fetch`, `updated_at`) VALUES ('6', 'Jugantor', 'https://www.jugantor.com/', 'scrape', '1', NULL, '.lead-news', '.news-item', 'h2 a', 'a[href^=\"/\"]', '', '', 'h1', '.content-details', '.news-image img', '.short-content', '.publish-date', '.author-name', '.pagination', '', '', '', '', '', '', '1800', '1', NULL, '2026-03-07 18:59:24', 'articles', '1', '0', '50', '2', NULL, 'none', NULL, NULL, '0', NULL, NULL, NULL, '2026-03-07 20:43:27');
INSERT INTO `autocontent_sources` (`id`, `name`, `url`, `type`, `category_id`, `selectors`, `selector_list_container`, `selector_list_item`, `selector_list_title`, `selector_list_link`, `selector_list_date`, `selector_list_image`, `selector_title`, `selector_content`, `selector_image`, `selector_excerpt`, `selector_date`, `selector_author`, `selector_pagination`, `selector_read_more`, `selector_category`, `selector_tags`, `selector_video`, `selector_audio`, `selector_source_url`, `fetch_interval`, `is_active`, `last_fetched_at`, `created_at`, `content_type`, `scrape_depth`, `use_browser`, `max_pages`, `delay`, `selector_list_url`, `pagination_type`, `pagination_selector`, `pagination_pattern`, `proxy_enabled`, `proxy_provider`, `proxy_config`, `last_fetch`, `updated_at`) VALUES ('7', 'Ittefaq', 'https://www.ittefaq.com.bd/', 'scrape', '1', NULL, '.news-list', '.news-item', 'h3 a', 'a[href^=\"/\"]', '', '', 'h1', '.news-details', '.image-content img', '.news-summary', '.time', '.reporter', '.pagination', '', '', '', '', '', '', '1800', '1', NULL, '2026-03-07 18:59:24', 'articles', '1', '0', '50', '2', NULL, 'none', NULL, NULL, '0', NULL, NULL, NULL, '2026-03-07 20:43:27');
INSERT INTO `autocontent_sources` (`id`, `name`, `url`, `type`, `category_id`, `selectors`, `selector_list_container`, `selector_list_item`, `selector_list_title`, `selector_list_link`, `selector_list_date`, `selector_list_image`, `selector_title`, `selector_content`, `selector_image`, `selector_excerpt`, `selector_date`, `selector_author`, `selector_pagination`, `selector_read_more`, `selector_category`, `selector_tags`, `selector_video`, `selector_audio`, `selector_source_url`, `fetch_interval`, `is_active`, `last_fetched_at`, `created_at`, `content_type`, `scrape_depth`, `use_browser`, `max_pages`, `delay`, `selector_list_url`, `pagination_type`, `pagination_selector`, `pagination_pattern`, `proxy_enabled`, `proxy_provider`, `proxy_config`, `last_fetch`, `updated_at`) VALUES ('8', 'Samakal', 'https://samakal.com/', 'scrape', '1', NULL, '.news-list', '.news-item', 'h2 a', 'a[href^=\"/\"]', '', '', 'h1', '.content-details', '.news-image img', '.news-excerpt', '.publish-time', '.author-name', '.pagination', '', '', '', '', '', '', '1800', '1', NULL, '2026-03-07 18:59:24', 'articles', '1', '0', '50', '2', NULL, 'none', NULL, NULL, '0', NULL, NULL, NULL, '2026-03-07 20:43:27');
INSERT INTO `autocontent_sources` (`id`, `name`, `url`, `type`, `category_id`, `selectors`, `selector_list_container`, `selector_list_item`, `selector_list_title`, `selector_list_link`, `selector_list_date`, `selector_list_image`, `selector_title`, `selector_content`, `selector_image`, `selector_excerpt`, `selector_date`, `selector_author`, `selector_pagination`, `selector_read_more`, `selector_category`, `selector_tags`, `selector_video`, `selector_audio`, `selector_source_url`, `fetch_interval`, `is_active`, `last_fetched_at`, `created_at`, `content_type`, `scrape_depth`, `use_browser`, `max_pages`, `delay`, `selector_list_url`, `pagination_type`, `pagination_selector`, `pagination_pattern`, `proxy_enabled`, `proxy_provider`, `proxy_config`, `last_fetch`, `updated_at`) VALUES ('9', 'TechCrunch', 'https://techcrunch.com/', 'scrape', '2', NULL, '.post-block', '.post-block', 'h2 a', 'a.post-block__title-link', '', '', 'meta[property=\"og:title\"]', '.article-content', 'meta[property=\"og:image\"]', 'meta[name=\"description\"]', 'time/@datetime', '.author-name', '.pagination', '', '', '', '', '', '', '600', '1', NULL, '2026-03-07 18:59:24', 'articles', '1', '0', '50', '2', NULL, 'none', NULL, NULL, '0', NULL, NULL, NULL, '2026-03-07 20:43:27');
INSERT INTO `autocontent_sources` (`id`, `name`, `url`, `type`, `category_id`, `selectors`, `selector_list_container`, `selector_list_item`, `selector_list_title`, `selector_list_link`, `selector_list_date`, `selector_list_image`, `selector_title`, `selector_content`, `selector_image`, `selector_excerpt`, `selector_date`, `selector_author`, `selector_pagination`, `selector_read_more`, `selector_category`, `selector_tags`, `selector_video`, `selector_audio`, `selector_source_url`, `fetch_interval`, `is_active`, `last_fetched_at`, `created_at`, `content_type`, `scrape_depth`, `use_browser`, `max_pages`, `delay`, `selector_list_url`, `pagination_type`, `pagination_selector`, `pagination_pattern`, `proxy_enabled`, `proxy_provider`, `proxy_config`, `last_fetch`, `updated_at`) VALUES ('10', 'The Verge', 'https://www.theverge.com/', 'scrape', '2', NULL, '.c-compact-river', '.c-compact-river__entry', 'h2 a', 'a[href^=\"/\"]', '', '', 'h1', '.c-article-body', '.c-article-lead-image img', '.c-summary-item', 'time/@datetime', '.c-byline__item', '.pagination', '', '', '', '', '', '', '600', '1', NULL, '2026-03-07 18:59:24', 'articles', '1', '0', '50', '2', NULL, 'none', NULL, NULL, '0', NULL, NULL, NULL, '2026-03-07 20:43:27');
INSERT INTO `autocontent_sources` (`id`, `name`, `url`, `type`, `category_id`, `selectors`, `selector_list_container`, `selector_list_item`, `selector_list_title`, `selector_list_link`, `selector_list_date`, `selector_list_image`, `selector_title`, `selector_content`, `selector_image`, `selector_excerpt`, `selector_date`, `selector_author`, `selector_pagination`, `selector_read_more`, `selector_category`, `selector_tags`, `selector_video`, `selector_audio`, `selector_source_url`, `fetch_interval`, `is_active`, `last_fetched_at`, `created_at`, `content_type`, `scrape_depth`, `use_browser`, `max_pages`, `delay`, `selector_list_url`, `pagination_type`, `pagination_selector`, `pagination_pattern`, `proxy_enabled`, `proxy_provider`, `proxy_config`, `last_fetch`, `updated_at`) VALUES ('11', 'BBC News', 'https://www.bbc.com/news', 'scrape', '3', NULL, '.gs-c-promo', '.gs-c-promo', 'h3 a', 'a[href^=\"/news/\"]', '', '', 'h1', '.article-body', '.article-body img', '.summary', 'time/@datetime', '.byline', '.pagination', '', '', '', '', '', '', '1800', '1', NULL, '2026-03-07 18:59:24', 'articles', '1', '0', '50', '2', NULL, 'none', NULL, NULL, '0', NULL, NULL, NULL, '2026-03-07 20:43:27');
INSERT INTO `autocontent_sources` (`id`, `name`, `url`, `type`, `category_id`, `selectors`, `selector_list_container`, `selector_list_item`, `selector_list_title`, `selector_list_link`, `selector_list_date`, `selector_list_image`, `selector_title`, `selector_content`, `selector_image`, `selector_excerpt`, `selector_date`, `selector_author`, `selector_pagination`, `selector_read_more`, `selector_category`, `selector_tags`, `selector_video`, `selector_audio`, `selector_source_url`, `fetch_interval`, `is_active`, `last_fetched_at`, `created_at`, `content_type`, `scrape_depth`, `use_browser`, `max_pages`, `delay`, `selector_list_url`, `pagination_type`, `pagination_selector`, `pagination_pattern`, `proxy_enabled`, `proxy_provider`, `proxy_config`, `last_fetch`, `updated_at`) VALUES ('12', 'CNN', 'https://www.cnn.com/', 'scrape', '3', NULL, '.cd__wrapper', '.cd__headline', 'span.cd__headline-text', 'a[href^=\"/\"]', '', '', 'h1', '.article-body', '.image-container img', '.lead-paragraph', 'div.timestamp', '.byline', '.pagination', '', '', '', '', '', '', '1800', '1', NULL, '2026-03-07 18:59:24', 'articles', '1', '0', '50', '2', NULL, 'none', NULL, NULL, '0', NULL, NULL, NULL, '2026-03-07 20:43:27');
INSERT INTO `autocontent_sources` (`id`, `name`, `url`, `type`, `category_id`, `selectors`, `selector_list_container`, `selector_list_item`, `selector_list_title`, `selector_list_link`, `selector_list_date`, `selector_list_image`, `selector_title`, `selector_content`, `selector_image`, `selector_excerpt`, `selector_date`, `selector_author`, `selector_pagination`, `selector_read_more`, `selector_category`, `selector_tags`, `selector_video`, `selector_audio`, `selector_source_url`, `fetch_interval`, `is_active`, `last_fetched_at`, `created_at`, `content_type`, `scrape_depth`, `use_browser`, `max_pages`, `delay`, `selector_list_url`, `pagination_type`, `pagination_selector`, `pagination_pattern`, `proxy_enabled`, `proxy_provider`, `proxy_config`, `last_fetch`, `updated_at`) VALUES ('13', 'Ars Technica', 'https://arstechnica.com/', 'scrape', '2', NULL, '.article', '.article', 'h2 a', 'a[href^=\"/\"]', '', '', 'h1', '.article-content', '.article-header img', '.excerpt', 'time/@datetime', '.author', '.pagination', '', '', '', '', '', '', '600', '1', NULL, '2026-03-07 18:59:24', 'articles', '1', '0', '50', '2', NULL, 'none', NULL, NULL, '0', NULL, NULL, NULL, '2026-03-07 20:43:27');
INSERT INTO `autocontent_sources` (`id`, `name`, `url`, `type`, `category_id`, `selectors`, `selector_list_container`, `selector_list_item`, `selector_list_title`, `selector_list_link`, `selector_list_date`, `selector_list_image`, `selector_title`, `selector_content`, `selector_image`, `selector_excerpt`, `selector_date`, `selector_author`, `selector_pagination`, `selector_read_more`, `selector_category`, `selector_tags`, `selector_video`, `selector_audio`, `selector_source_url`, `fetch_interval`, `is_active`, `last_fetched_at`, `created_at`, `content_type`, `scrape_depth`, `use_browser`, `max_pages`, `delay`, `selector_list_url`, `pagination_type`, `pagination_selector`, `pagination_pattern`, `proxy_enabled`, `proxy_provider`, `proxy_config`, `last_fetch`, `updated_at`) VALUES ('14', 'Wired', 'https://www.wired.com/', 'scrape', '2', NULL, '.SummaryItemWrapper', '.SummaryItemWrapper', 'h3 a', 'a[href^=\"/story/\"]', '', '', 'h1', '.article-body', '.article-hero-image img', '.summary', 'time/@datetime', '.byline', '.pagination', '', '', '', '', '', '', '600', '1', NULL, '2026-03-07 18:59:24', 'articles', '1', '0', '50', '2', NULL, 'none', NULL, NULL, '0', NULL, NULL, NULL, '2026-03-07 20:43:27');
INSERT INTO `autocontent_sources` (`id`, `name`, `url`, `type`, `category_id`, `selectors`, `selector_list_container`, `selector_list_item`, `selector_list_title`, `selector_list_link`, `selector_list_date`, `selector_list_image`, `selector_title`, `selector_content`, `selector_image`, `selector_excerpt`, `selector_date`, `selector_author`, `selector_pagination`, `selector_read_more`, `selector_category`, `selector_tags`, `selector_video`, `selector_audio`, `selector_source_url`, `fetch_interval`, `is_active`, `last_fetched_at`, `created_at`, `content_type`, `scrape_depth`, `use_browser`, `max_pages`, `delay`, `selector_list_url`, `pagination_type`, `pagination_selector`, `pagination_pattern`, `proxy_enabled`, `proxy_provider`, `proxy_config`, `last_fetch`, `updated_at`) VALUES ('15', 'Prothom Alo RSS', 'https://feeds.feedburner.com/prothomalo/latest', 'rss', '1', NULL, '', '', '', '', '', '', 'title', 'description', 'media:content', 'description', 'pubDate', 'author', '', '', '', '', '', '', '', '1800', '1', NULL, '2026-03-07 18:59:24', 'articles', '1', '0', '50', '2', NULL, 'none', NULL, NULL, '0', NULL, NULL, NULL, '2026-03-07 20:43:27');
INSERT INTO `autocontent_sources` (`id`, `name`, `url`, `type`, `category_id`, `selectors`, `selector_list_container`, `selector_list_item`, `selector_list_title`, `selector_list_link`, `selector_list_date`, `selector_list_image`, `selector_title`, `selector_content`, `selector_image`, `selector_excerpt`, `selector_date`, `selector_author`, `selector_pagination`, `selector_read_more`, `selector_category`, `selector_tags`, `selector_video`, `selector_audio`, `selector_source_url`, `fetch_interval`, `is_active`, `last_fetched_at`, `created_at`, `content_type`, `scrape_depth`, `use_browser`, `max_pages`, `delay`, `selector_list_url`, `pagination_type`, `pagination_selector`, `pagination_pattern`, `proxy_enabled`, `proxy_provider`, `proxy_config`, `last_fetch`, `updated_at`) VALUES ('16', 'BBC World RSS', 'http://feeds.bbci.co.uk/news/world/rss.xml', 'rss', '3', NULL, '', '', '', '', '', '', 'title', 'description', 'media:content', 'description', 'pubDate', 'author', '', '', '', '', '', '', '', '1800', '1', NULL, '2026-03-07 18:59:24', 'articles', '1', '0', '50', '2', NULL, 'none', NULL, NULL, '0', NULL, NULL, NULL, '2026-03-07 20:43:27');
INSERT INTO `autocontent_sources` (`id`, `name`, `url`, `type`, `category_id`, `selectors`, `selector_list_container`, `selector_list_item`, `selector_list_title`, `selector_list_link`, `selector_list_date`, `selector_list_image`, `selector_title`, `selector_content`, `selector_image`, `selector_excerpt`, `selector_date`, `selector_author`, `selector_pagination`, `selector_read_more`, `selector_category`, `selector_tags`, `selector_video`, `selector_audio`, `selector_source_url`, `fetch_interval`, `is_active`, `last_fetched_at`, `created_at`, `content_type`, `scrape_depth`, `use_browser`, `max_pages`, `delay`, `selector_list_url`, `pagination_type`, `pagination_selector`, `pagination_pattern`, `proxy_enabled`, `proxy_provider`, `proxy_config`, `last_fetch`, `updated_at`) VALUES ('17', 'BBC Travel', 'https://www.bbc.com/travel', 'scrape', '4', NULL, '.content--list', '.media-list__item', 'h3 a, .media__title a', 'a[href]', 'time', '', 'h1', 'article', '.article-hero-image img', '.summary', 'time', '.author', '.pagination', '', '', '', '', '', '', '3600', '1', '2026-03-07 19:14:14', '2026-03-07 18:59:24', 'articles', '1', '0', '50', '2', NULL, 'none', NULL, NULL, '0', NULL, NULL, NULL, '2026-03-07 20:43:27');
INSERT INTO `autocontent_sources` (`id`, `name`, `url`, `type`, `category_id`, `selectors`, `selector_list_container`, `selector_list_item`, `selector_list_title`, `selector_list_link`, `selector_list_date`, `selector_list_image`, `selector_title`, `selector_content`, `selector_image`, `selector_excerpt`, `selector_date`, `selector_author`, `selector_pagination`, `selector_read_more`, `selector_category`, `selector_tags`, `selector_video`, `selector_audio`, `selector_source_url`, `fetch_interval`, `is_active`, `last_fetched_at`, `created_at`, `content_type`, `scrape_depth`, `use_browser`, `max_pages`, `delay`, `selector_list_url`, `pagination_type`, `pagination_selector`, `pagination_pattern`, `proxy_enabled`, `proxy_provider`, `proxy_config`, `last_fetch`, `updated_at`) VALUES ('18', 'BBC Food', 'https://www.bbc.com/food', 'scrape', '4', NULL, '.recipe', '.recipe', 'h3 a', 'a[href]', '', '', 'h1', '.recipe-body', '.recipe-media img', '.recipe-description', 'time', '.author', '.pagination', '', '', '', '', '', '', '3600', '1', '2026-03-07 19:10:39', '2026-03-07 18:59:24', 'articles', '1', '0', '50', '2', NULL, 'none', NULL, NULL, '0', NULL, NULL, NULL, '2026-03-07 20:43:27');
INSERT INTO `autocontent_sources` (`id`, `name`, `url`, `type`, `category_id`, `selectors`, `selector_list_container`, `selector_list_item`, `selector_list_title`, `selector_list_link`, `selector_list_date`, `selector_list_image`, `selector_title`, `selector_content`, `selector_image`, `selector_excerpt`, `selector_date`, `selector_author`, `selector_pagination`, `selector_read_more`, `selector_category`, `selector_tags`, `selector_video`, `selector_audio`, `selector_source_url`, `fetch_interval`, `is_active`, `last_fetched_at`, `created_at`, `content_type`, `scrape_depth`, `use_browser`, `max_pages`, `delay`, `selector_list_url`, `pagination_type`, `pagination_selector`, `pagination_pattern`, `proxy_enabled`, `proxy_provider`, `proxy_config`, `last_fetch`, `updated_at`) VALUES ('19', 'Prothom Alo Latest', 'https://www.prothomalo.com/', 'html', '1', NULL, '.wide-story-card, .news_with_item', '.news-item', 'h3 a', '', '', '', '.story-title h1', '.story-element-text', '.Td4Ec img', '', '', '', '', '', '', '', '', '', '', '1800', '1', NULL, '2026-03-07 20:43:27', 'articles', '1', '0', '50', '2', NULL, 'link', NULL, NULL, '0', NULL, NULL, NULL, '2026-03-07 20:43:27');
INSERT INTO `autocontent_sources` (`id`, `name`, `url`, `type`, `category_id`, `selectors`, `selector_list_container`, `selector_list_item`, `selector_list_title`, `selector_list_link`, `selector_list_date`, `selector_list_image`, `selector_title`, `selector_content`, `selector_image`, `selector_excerpt`, `selector_date`, `selector_author`, `selector_pagination`, `selector_read_more`, `selector_category`, `selector_tags`, `selector_video`, `selector_audio`, `selector_source_url`, `fetch_interval`, `is_active`, `last_fetched_at`, `created_at`, `content_type`, `scrape_depth`, `use_browser`, `max_pages`, `delay`, `selector_list_url`, `pagination_type`, `pagination_selector`, `pagination_pattern`, `proxy_enabled`, `proxy_provider`, `proxy_config`, `last_fetch`, `updated_at`) VALUES ('20', 'BD News 24 Bengali', 'https://bangla.bdnews24.com/', 'html', '1', NULL, '.col-md-3', '.SubCat-wrapper', 'h5 a', '', '', '', '.details-title h1', '#contentDetails', '.details-img img', '', '', '', '', '', '', '', '', '', '', '1800', '1', NULL, '2026-03-07 20:43:27', 'articles', '1', '0', '50', '2', NULL, 'link', NULL, NULL, '0', NULL, NULL, NULL, '2026-03-07 20:43:27');
INSERT INTO `autocontent_sources` (`id`, `name`, `url`, `type`, `category_id`, `selectors`, `selector_list_container`, `selector_list_item`, `selector_list_title`, `selector_list_link`, `selector_list_date`, `selector_list_image`, `selector_title`, `selector_content`, `selector_image`, `selector_excerpt`, `selector_date`, `selector_author`, `selector_pagination`, `selector_read_more`, `selector_category`, `selector_tags`, `selector_video`, `selector_audio`, `selector_source_url`, `fetch_interval`, `is_active`, `last_fetched_at`, `created_at`, `content_type`, `scrape_depth`, `use_browser`, `max_pages`, `delay`, `selector_list_url`, `pagination_type`, `pagination_selector`, `pagination_pattern`, `proxy_enabled`, `proxy_provider`, `proxy_config`, `last_fetch`, `updated_at`) VALUES ('21', 'BBC Bangla', 'https://www.bbc.com/bengali', 'html', '1', NULL, '.bbc-1kr7d6c', '.bbc-1kr7d6c', 'h3 a', '', '', '', 'h1', '.article-body', '.article-hero-image img', '', '', '', '', '', '', '', '', '', '', '1800', '1', NULL, '2026-03-07 20:43:27', 'articles', '1', '0', '50', '2', NULL, 'link', NULL, NULL, '0', NULL, NULL, NULL, '2026-03-07 20:43:27');
INSERT INTO `autocontent_sources` (`id`, `name`, `url`, `type`, `category_id`, `selectors`, `selector_list_container`, `selector_list_item`, `selector_list_title`, `selector_list_link`, `selector_list_date`, `selector_list_image`, `selector_title`, `selector_content`, `selector_image`, `selector_excerpt`, `selector_date`, `selector_author`, `selector_pagination`, `selector_read_more`, `selector_category`, `selector_tags`, `selector_video`, `selector_audio`, `selector_source_url`, `fetch_interval`, `is_active`, `last_fetched_at`, `created_at`, `content_type`, `scrape_depth`, `use_browser`, `max_pages`, `delay`, `selector_list_url`, `pagination_type`, `pagination_selector`, `pagination_pattern`, `proxy_enabled`, `proxy_provider`, `proxy_config`, `last_fetch`, `updated_at`) VALUES ('22', 'Daily Star Bangla', 'https://www.thedailystar.net/bangla', 'html', '1', NULL, '.view-content', '.views-row', 'h2 a', '', '', '', 'h1', '.field-name-body', '.field-name-field-image img', '', '', '', '', '', '', '', '', '', '', '1800', '1', NULL, '2026-03-07 20:43:27', 'articles', '1', '0', '50', '2', NULL, 'link', NULL, NULL, '0', NULL, NULL, NULL, '2026-03-07 20:43:27');
INSERT INTO `autocontent_sources` (`id`, `name`, `url`, `type`, `category_id`, `selectors`, `selector_list_container`, `selector_list_item`, `selector_list_title`, `selector_list_link`, `selector_list_date`, `selector_list_image`, `selector_title`, `selector_content`, `selector_image`, `selector_excerpt`, `selector_date`, `selector_author`, `selector_pagination`, `selector_read_more`, `selector_category`, `selector_tags`, `selector_video`, `selector_audio`, `selector_source_url`, `fetch_interval`, `is_active`, `last_fetched_at`, `created_at`, `content_type`, `scrape_depth`, `use_browser`, `max_pages`, `delay`, `selector_list_url`, `pagination_type`, `pagination_selector`, `pagination_pattern`, `proxy_enabled`, `proxy_provider`, `proxy_config`, `last_fetch`, `updated_at`) VALUES ('23', 'NTV Bangla', 'https://www.ntvbd.com/bangla', 'html', '1', NULL, '.news-list', '.news-item', 'h3 a', '', '', '', 'h1', '.news-details', '.news-image img', '', '', '', '', '', '', '', '', '', '', '1800', '1', NULL, '2026-03-07 20:43:27', 'articles', '1', '0', '50', '2', NULL, 'link', NULL, NULL, '0', NULL, NULL, NULL, '2026-03-07 20:43:27');
INSERT INTO `autocontent_sources` (`id`, `name`, `url`, `type`, `category_id`, `selectors`, `selector_list_container`, `selector_list_item`, `selector_list_title`, `selector_list_link`, `selector_list_date`, `selector_list_image`, `selector_title`, `selector_content`, `selector_image`, `selector_excerpt`, `selector_date`, `selector_author`, `selector_pagination`, `selector_read_more`, `selector_category`, `selector_tags`, `selector_video`, `selector_audio`, `selector_source_url`, `fetch_interval`, `is_active`, `last_fetched_at`, `created_at`, `content_type`, `scrape_depth`, `use_browser`, `max_pages`, `delay`, `selector_list_url`, `pagination_type`, `pagination_selector`, `pagination_pattern`, `proxy_enabled`, `proxy_provider`, `proxy_config`, `last_fetch`, `updated_at`) VALUES ('24', 'Jugantor', 'https://www.jugantor.com/', 'html', '1', NULL, '.lead-news', '.news-item', 'h2 a', '', '', '', 'h1', '.content-details', '.news-image img', '', '', '', '', '', '', '', '', '', '', '1800', '1', NULL, '2026-03-07 20:43:27', 'articles', '1', '0', '50', '2', NULL, 'link', NULL, NULL, '0', NULL, NULL, NULL, '2026-03-07 20:43:27');
INSERT INTO `autocontent_sources` (`id`, `name`, `url`, `type`, `category_id`, `selectors`, `selector_list_container`, `selector_list_item`, `selector_list_title`, `selector_list_link`, `selector_list_date`, `selector_list_image`, `selector_title`, `selector_content`, `selector_image`, `selector_excerpt`, `selector_date`, `selector_author`, `selector_pagination`, `selector_read_more`, `selector_category`, `selector_tags`, `selector_video`, `selector_audio`, `selector_source_url`, `fetch_interval`, `is_active`, `last_fetched_at`, `created_at`, `content_type`, `scrape_depth`, `use_browser`, `max_pages`, `delay`, `selector_list_url`, `pagination_type`, `pagination_selector`, `pagination_pattern`, `proxy_enabled`, `proxy_provider`, `proxy_config`, `last_fetch`, `updated_at`) VALUES ('25', 'Ittefaq', 'https://www.ittefaq.com.bd/', 'html', '1', NULL, '.news-list', '.news-item', 'h3 a', '', '', '', 'h1', '.news-details', '.image-content img', '', '', '', '', '', '', '', '', '', '', '1800', '1', NULL, '2026-03-07 20:43:27', 'articles', '1', '0', '50', '2', NULL, 'link', NULL, NULL, '0', NULL, NULL, NULL, '2026-03-07 20:43:27');
INSERT INTO `autocontent_sources` (`id`, `name`, `url`, `type`, `category_id`, `selectors`, `selector_list_container`, `selector_list_item`, `selector_list_title`, `selector_list_link`, `selector_list_date`, `selector_list_image`, `selector_title`, `selector_content`, `selector_image`, `selector_excerpt`, `selector_date`, `selector_author`, `selector_pagination`, `selector_read_more`, `selector_category`, `selector_tags`, `selector_video`, `selector_audio`, `selector_source_url`, `fetch_interval`, `is_active`, `last_fetched_at`, `created_at`, `content_type`, `scrape_depth`, `use_browser`, `max_pages`, `delay`, `selector_list_url`, `pagination_type`, `pagination_selector`, `pagination_pattern`, `proxy_enabled`, `proxy_provider`, `proxy_config`, `last_fetch`, `updated_at`) VALUES ('26', 'Samakal', 'https://samakal.com/', 'html', '1', NULL, '.news-list', '.news-item', 'h2 a', '', '', '', 'h1', '.content-details', '.news-image img', '', '', '', '', '', '', '', '', '', '', '1800', '1', NULL, '2026-03-07 20:43:27', 'articles', '1', '0', '50', '2', NULL, 'link', NULL, NULL, '0', NULL, NULL, NULL, '2026-03-07 20:43:27');
INSERT INTO `autocontent_sources` (`id`, `name`, `url`, `type`, `category_id`, `selectors`, `selector_list_container`, `selector_list_item`, `selector_list_title`, `selector_list_link`, `selector_list_date`, `selector_list_image`, `selector_title`, `selector_content`, `selector_image`, `selector_excerpt`, `selector_date`, `selector_author`, `selector_pagination`, `selector_read_more`, `selector_category`, `selector_tags`, `selector_video`, `selector_audio`, `selector_source_url`, `fetch_interval`, `is_active`, `last_fetched_at`, `created_at`, `content_type`, `scrape_depth`, `use_browser`, `max_pages`, `delay`, `selector_list_url`, `pagination_type`, `pagination_selector`, `pagination_pattern`, `proxy_enabled`, `proxy_provider`, `proxy_config`, `last_fetch`, `updated_at`) VALUES ('27', 'NID Service', 'https://www.bdcgny.org/nid', 'scrape', '0', NULL, '//body', './/div[contains(@class, &quot;item&quot;) or contains(@class, &quot;post&quot;) or contains(@class, &quot;article&quot;) or contains(@class, &quot;story&quot;) or contains(@class, &quot;news&quot;)]', './/a[string-length(text()) &gt; 10]', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '120', '1', NULL, '2026-03-07 22:19:12', 'pages', '1', '1', '50', '2', NULL, 'none', NULL, NULL, '0', NULL, NULL, NULL, '2026-03-07 22:19:12');
