<?php

/**
 * app/Helpers/DocxHelper.php
 *
 * CV to DOCX export helper using PhpOffice/PhpWord.
 * Generates a Word document from CV sections and items.
 */

if (!function_exists('cvGenerateDocx')) {
    /**
     * Generate a DOCX file from CV data and stream it for download.
     *
     * @param array $cv          CV metadata (id, title, etc.)
     * @param array $sections    CV sections with items
     * @param string $filename   Output filename (without .docx)
     * @param array $options     Optional overrides
     * @return bool
     */
    function cvGenerateDocx(array $cv, array $sections, string $filename = 'CV', array $options = []): bool
    {
        if (!class_exists(\PhpOffice\PhpWord\PhpWord::class)) {
            if (function_exists('logError')) {
                logError('PhpOffice/PhpWord not installed');
            }
            http_response_code(500);
            echo 'DOCX generation requires PhpOffice/PhpWord. Run: composer require phpoffice/phpword';
            return false;
        }

        try {
            $phpWord = new \PhpOffice\PhpWord\PhpWord();

            // Document defaults
            $phpWord->setDefaultFontName('Calibri');
            $phpWord->setDefaultFontSize(11);

            // Metadata
            $properties = $phpWord->getDocInfo();
            $properties->setCreator($options['creator'] ?? 'BroxLab CV Builder');
            $properties->setTitle($filename);
            $properties->setDescription('CV generated by BroxLab CV Builder');

            $section = $phpWord->addSection([
                'marginTop' => 1440,   // 1 inch in twips
                'marginBottom' => 1440,
                'marginLeft' => 1440,
                'marginRight' => 1440,
            ]);

            // ========== HEADER ==========
            $section->addTitle($cv['title'] ?? 'CV', 1);
            $section->addTextBreak(0.5);

            // ========== SECTIONS ==========
            foreach ($sections as $sectionData) {
                if (empty($sectionData['items'])) {
                    continue;
                }

                $sectionType = $sectionData['section_type'] ?? '';
                $sectionTitle = $sectionData['title'] ?? ucfirst($sectionType);

                // Section heading
                $section->addTitle($sectionTitle, 2);
                $section->addTextBreak(0.3);

                switch ($sectionType) {
                    case 'summary':
                        foreach ($sectionData['items'] as $item) {
                            $content = $item['content'] ?? [];
                            $text = $content['text'] ?? $content['summary'] ?? '';
                            if (!empty($text)) {
                                $section->addText($text, ['italic' => true, 'size' => 11]);
                            }
                        }
                        break;

                    case 'experience':
                        foreach ($sectionData['items'] as $item) {
                            $c = $item['content'] ?? [];
                            $position = $c['position'] ?? '';
                            $company = $c['company'] ?? '';
                            $location = $c['location'] ?? '';
                            $startDate = $c['start_date'] ?? '';
                            $endDate = $c['end_date'] ?? 'Present';
                            $description = $c['description'] ?? $c['responsibilities'] ?? '';

                            // Position (bold)
                            $headerText = $position;
                            if ($company) {
                                $headerText .= $company ? ' — ' . $company : '';
                            }
                            if (!empty($headerText)) {
                                $section->addText($headerText, ['bold' => true, 'size' => 11]);
                            }

                            // Location + dates
                            $metaParts = [];
                            if ($location) $metaParts[] = $location;
                            if ($startDate) $metaParts[] = $startDate . ' — ' . $endDate;
                            if (!empty($metaParts)) {
                                $section->addText(implode(' | ', $metaParts), ['italic' => true, 'size' => 10, 'color' => '555555']);
                            }

                            // Description
                            if (!empty($description)) {
                                // Check for bullet points (newline separated or markdown list)
                                $lines = preg_split('/\n|\r\n?/', $description);
                                $hasBullets = false;
                                foreach ($lines as $line) {
                                    $line = trim($line);
                                    if (empty($line)) continue;
                                    if (preg_match('/^[\s]*[-*•]\s/', $line)) {
                                        $line = preg_replace('/^[\s]*[-*•]\s/', '', $line);
                                        $section->addListItem($line, 0, ['size' => 10]);
                                        $hasBullets = true;
                                    } else {
                                        if ($hasBullets) {
                                            $section->addListItem($line, 0, ['size' => 10]);
                                        } else {
                                            $section->addText($line, ['size' => 10]);
                                        }
                                    }
                                }
                            }
                            $section->addTextBreak(0.2);
                        }
                        break;

                    case 'education':
                        foreach ($sectionData['items'] as $item) {
                            $c = $item['content'] ?? [];
                            $degree = $c['degree'] ?? '';
                            $institution = $c['institution'] ?? '';
                            $field = $c['field'] ?? '';
                            $startDate = $c['start_date'] ?? $c['start_year'] ?? '';
                            $endDate = $c['end_date'] ?? $c['end_year'] ?? '';
                            $gpa = $c['gpa'] ?? '';

                            $headerText = $degree;
                            if ($field) $headerText .= ($headerText ? ' in ' : '') . $field;
                            if (!empty($headerText)) {
                                $section->addText($headerText, ['bold' => true, 'size' => 11]);
                            }

                            $metaParts = [];
                            if ($institution) $metaParts[] = $institution;
                            if ($startDate || $endDate) {
                                $metaParts[] = ($startDate ?: '') . ' — ' . ($endDate ?: 'Present');
                            }
                            if (!empty($metaParts)) {
                                $section->addText(implode(' | ', $metaParts), ['italic' => true, 'size' => 10, 'color' => '555555']);
                            }
                            if ($gpa) {
                                $section->addText('GPA: ' . $gpa, ['size' => 10]);
                            }
                            $section->addTextBreak(0.2);
                        }
                        break;

                    case 'skills':
                        $allSkills = [];
                        foreach ($sectionData['items'] as $item) {
                            $c = $item['content'] ?? [];
                            if (!empty($c['name'])) {
                                $allSkills[] = $c['name'];
                            }
                            // Handle array-style skills from builder
                            if (!empty($c['technical'])) {
                                foreach ((array)$c['technical'] as $s) {
                                    if (!empty(trim($s))) $allSkills[] = trim($s);
                                }
                            }
                            if (!empty($c['soft'])) {
                                foreach ((array)$c['soft'] as $s) {
                                    if (!empty(trim($s))) $allSkills[] = trim($s);
                                }
                            }
                            if (!empty($c['languages'])) {
                                foreach ((array)$c['languages'] as $s) {
                                    if (!empty(trim($s))) $allSkills[] = trim($s);
                                }
                            }
                            if (!empty($c['skills']) && is_array($c['skills'])) {
                                foreach ($c['skills'] as $s) {
                                    if (!empty(trim($s))) $allSkills[] = trim($s);
                                }
                            }
                        }
                        $allSkills = array_unique($allSkills);
                        if (!empty($allSkills)) {
                            $section->addText(implode(', ', $allSkills), ['size' => 10]);
                        }
                        break;

                    case 'projects':
                        foreach ($sectionData['items'] as $item) {
                            $c = $item['content'] ?? [];
                            $name = $c['name'] ?? '';
                            $description = $c['description'] ?? '';
                            $technologies = $c['technologies'] ?? '';
                            $url = $c['url'] ?? '';

                            if (!empty($name)) {
                                $section->addText($name, ['bold' => true, 'size' => 11]);
                            }
                            if (!empty($technologies)) {
                                $section->addText('Technologies: ' . $technologies, ['italic' => true, 'size' => 10, 'color' => '555555']);
                            }
                            if (!empty($description)) {
                                $section->addText($description, ['size' => 10]);
                            }
                            if (!empty($url)) {
                                $section->addText($url, ['size' => 10, 'color' => '0563C1']);
                            }
                            $section->addTextBreak(0.2);
                        }
                        break;

                    case 'certifications':
                    case 'certificates':
                        foreach ($sectionData['items'] as $item) {
                            $c = $item['content'] ?? [];
                            $name = $c['name'] ?? '';
                            $issuer = $c['issuer'] ?? $c['organization'] ?? '';
                            $date = $c['date'] ?? $c['issue_date'] ?? '';

                            $headerText = $name;
                            if (!empty($headerText)) {
                                $section->addText($headerText, ['bold' => true, 'size' => 11]);
                            }
                            $metaParts = [];
                            if ($issuer) $metaParts[] = $issuer;
                            if ($date) $metaParts[] = $date;
                            if (!empty($metaParts)) {
                                $section->addText(implode(' | ', $metaParts), ['italic' => true, 'size' => 10, 'color' => '555555']);
                            }
                            $section->addTextBreak(0.2);
                        }
                        break;

                    case 'references':
                        foreach ($sectionData['items'] as $item) {
                            $c = $item['content'] ?? [];
                            $name = $c['name'] ?? '';
                            $title = $c['title'] ?? '';
                            $email = $c['email'] ?? '';
                            $phone = $c['phone'] ?? '';
                            $company = $c['company'] ?? '';

                            if (!empty($name)) {
                                $section->addText($name, ['bold' => true, 'size' => 11]);
                            }
                            $metaParts = [];
                            if ($title) $metaParts[] = $title;
                            if ($company) $metaParts[] = $company;
                            if ($email) $metaParts[] = $email;
                            if ($phone) $metaParts[] = $phone;
                            if (!empty($metaParts)) {
                                $section->addText(implode(' | ', $metaParts), ['size' => 10, 'color' => '555555']);
                            }
                            $section->addTextBreak(0.2);
                        }
                        break;

                    default:
                        foreach ($sectionData['items'] as $item) {
                            $c = $item['content'] ?? [];
                            $text = is_string($c) ? $c : ($c['text'] ?? $c['content'] ?? '');
                            if (!empty($text)) {
                                $section->addText($text, ['size' => 10]);
                            }
                        }
                        break;
                }

                $section->addTextBreak(0.5);
            }

            // ========== OUTPUT ==========
            if (!preg_match('/\.docx$/i', $filename)) {
                $filename .= '.docx';
            }

            // Clean output buffer
            if (ob_get_level() > 0) {
                ob_clean();
            }

            header('Content-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.document');
            header('Content-Disposition: attachment; filename="' . basename($filename) . '"');
            header('Cache-Control: max-age=0');

            $writer = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord, 'Word2007');
            $writer->save('php://output');
            exit;

        } catch (Throwable $e) {
            if (function_exists('logError')) {
                logError('DOCX generation failed: ' . $e->getMessage());
            }
            http_response_code(500);
            echo 'Failed to generate DOCX: ' . $e->getMessage();
            return false;
        }
    }
}
