<?php

namespace App\Http\Controllers;

use App\Support\MedicinesDataService;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

/**
 * Port of legacy app/Controllers/SitemapController.php — robots.txt + the
 * split XML sitemap system. All responses are XML with 24h cache headers.
 */
class SitemapController extends Controller
{
    /** @var array<int, array{loc:string, priority:float, changefreq:string}> */
    protected array $staticPages = [
        ['loc' => '/', 'priority' => 1.0, 'changefreq' => 'daily'],
        ['loc' => '/about-us', 'priority' => 0.8, 'changefreq' => 'monthly'],
        ['loc' => '/contact', 'priority' => 0.7, 'changefreq' => 'monthly'],
        ['loc' => '/advertise', 'priority' => 0.7, 'changefreq' => 'monthly'],
        ['loc' => '/donate', 'priority' => 0.6, 'changefreq' => 'monthly'],
        ['loc' => '/faq', 'priority' => 0.7, 'changefreq' => 'monthly'],
        ['loc' => '/terms', 'priority' => 0.4, 'changefreq' => 'yearly'],
        ['loc' => '/privacy', 'priority' => 0.4, 'changefreq' => 'yearly'],
        ['loc' => '/newsletter', 'priority' => 0.6, 'changefreq' => 'monthly'],
        ['loc' => '/bangla-converter', 'priority' => 0.6, 'changefreq' => 'monthly'],
        ['loc' => '/ramadan-2026', 'priority' => 0.7, 'changefreq' => 'monthly'],
        ['loc' => '/medicines', 'priority' => 0.8, 'changefreq' => 'weekly'],
        ['loc' => '/medicines/details', 'priority' => 0.6, 'changefreq' => 'monthly'],
        ['loc' => '/calculators', 'priority' => 0.7, 'changefreq' => 'weekly'],
        ['loc' => '/weather', 'priority' => 0.6, 'changefreq' => 'daily'],
        ['loc' => '/weather/details', 'priority' => 0.5, 'changefreq' => 'monthly'],
        ['loc' => '/services', 'priority' => 0.7, 'changefreq' => 'weekly'],
        ['loc' => '/mobiles', 'priority' => 0.6, 'changefreq' => 'weekly'],
        ['loc' => '/posts', 'priority' => 0.6, 'changefreq' => 'weekly'],
        ['loc' => '/categories', 'priority' => 0.5, 'changefreq' => 'weekly'],
        ['loc' => '/tags', 'priority' => 0.5, 'changefreq' => 'weekly'],
    ];

    public function robots(): Response
    {
        $sitemapUrl = url('/sitemap.xml');

        $content = "# robots.txt - dynamically generated by BroxLab\n"
            . "# Served by the application so the sitemap host matches the current environment\n\n"
            . "User-agent: *\n"
            . "Allow: /\n\n"
            . "Disallow: /admin/\n"
            . "Disallow: /user/private/\n"
            . "Disallow: /api/\n\n"
            . "Sitemap: {$sitemapUrl}\n\n"
            . "User-agent: Googlebot\n"
            . "Allow: /\n\n"
            . "User-agent: Bingbot\n"
            . "Allow: /\n";

        return response($content, 200, [
            'Content-Type' => 'text/plain; charset=utf-8',
        ]);
    }

    /** GET /sitemap.xml — sitemap index. */
    public function index(): Response
    {
        $latest = fn (string $table, string $column = 'updated_at') => DB::table($table)
            ->max($column) ?: now()->toDateString();

        $sitemaps = [
            ['loc' => '/sitemap-posts.xml', 'lastmod' => date('Y-m-d', strtotime($latest('posts', 'updated_at')))],
            ['loc' => '/sitemap-pages.xml', 'lastmod' => date('Y-m-d', strtotime($latest('pages', 'updated_at')))],
            ['loc' => '/sitemap-categories.xml', 'lastmod' => now()->toDateString()],
            ['loc' => '/sitemap-tags.xml', 'lastmod' => now()->toDateString()],
            ['loc' => '/sitemap-services.xml', 'lastmod' => date('Y-m-d', strtotime($latest('services', 'updated_at')))],
            ['loc' => '/sitemap-mobiles.xml', 'lastmod' => date('Y-m-d', strtotime($latest('mobiles', 'created_at')))],
            ['loc' => '/sitemap-static.xml', 'lastmod' => now()->toDateString()],
            ['loc' => '/sitemap-medex-brands.xml', 'lastmod' => now()->toDateString()],
        ];

        $xml = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
            . "<sitemapindex xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">\n";

        foreach ($sitemaps as $map) {
            $loc = url(rtrim($map['loc'], '/'));
            $xml .= " <sitemap>\n"
                . "  <loc>{$loc}</loc>\n"
                . "  <lastmod>{$map['lastmod']}</lastmod>\n"
                . " </sitemap>\n";
        }

        $xml .= "</sitemapindex>\n";

        return $this->xml($xml);
    }

    /** GET /sitemap-posts.xml */
    public function posts(): Response
    {
        $items = $this->safe(fn () => DB::table('posts')
            ->where('published', 1)
            ->orderByDesc('updated_at')
            ->limit(2000)
            ->get(['id', 'slug', 'updated_at']));

        $xml = $this->openUrlset();
        foreach ($items as $item) {
            $loc = url('/posts/' . $item->id . '/' . urlencode((string) $item->slug));
            $xml .= $this->url($loc, date('Y-m-d', strtotime((string) $item->updated_at)), 'weekly', 0.9);
        }

        return $this->xml($xml . $this->closeUrlset());
    }

    /** GET /sitemap-pages.xml */
    public function pages(): Response
    {
        $items = $this->safe(fn () => DB::table('pages')
            ->where('published', 1)
            ->orderByDesc('updated_at')
            ->limit(1000)
            ->get(['slug', 'updated_at']));

        $xml = $this->openUrlset();
        foreach ($items as $item) {
            $loc = url('/pages/view/' . urlencode((string) $item->slug));
            $xml .= $this->url($loc, date('Y-m-d', strtotime((string) $item->updated_at)), 'monthly', 0.7);
        }

        return $this->xml($xml . $this->closeUrlset());
    }

    /** GET /sitemap-categories.xml */
    public function categories(): Response
    {
        $items = $this->safe(fn () => DB::table('categories')->orderBy('name')->get(['slug']));

        $xml = $this->openUrlset();
        foreach ($items as $item) {
            $loc = url('/category/' . urlencode((string) $item->slug));
            $xml .= $this->url($loc, now()->toDateString(), 'weekly', 0.6);
        }

        return $this->xml($xml . $this->closeUrlset());
    }

    /** GET /sitemap-tags.xml */
    public function tags(): Response
    {
        $items = $this->safe(fn () => DB::table('tags')->orderBy('name')->get(['slug']));

        $xml = $this->openUrlset();
        foreach ($items as $item) {
            $loc = url('/tag/' . urlencode((string) $item->slug));
            $xml .= $this->url($loc, now()->toDateString(), 'weekly', 0.5);
        }

        return $this->xml($xml . $this->closeUrlset());
    }

    /** GET /sitemap-services.xml */
    public function services(): Response
    {
        $items = $this->safe(fn () => DB::table('services')
            ->whereIn('status', ['active', 'archived'])
            ->whereNull('deleted_at')
            ->orderByDesc('updated_at')
            ->limit(1000)
            ->get(['slug', 'updated_at']));

        $xml = $this->openUrlset();
        foreach ($items as $item) {
            $loc = url('/services/view/' . urlencode((string) $item->slug));
            $xml .= $this->url($loc, date('Y-m-d', strtotime((string) $item->updated_at)), 'weekly', 0.8);
        }

        return $this->xml($xml . $this->closeUrlset());
    }

    /** GET /sitemap-mobiles.xml */
    public function mobiles(): Response
    {
        $items = $this->safe(fn () => DB::table('mobiles')
            ->orderByDesc('created_at')
            ->limit(2000)
            ->get(['id', 'created_at']));

        $xml = $this->openUrlset();
        foreach ($items as $item) {
            $loc = url('/mobiles/view/' . (int) $item->id);
            $xml .= $this->url($loc, date('Y-m-d', strtotime((string) $item->created_at)), 'monthly', 0.6);
        }

        return $this->xml($xml . $this->closeUrlset());
    }

    /** GET /sitemap-static.xml */
    public function staticPages(): Response
    {
        $xml = $this->openUrlset();
        foreach ($this->staticPages as $page) {
            $loc = url(rtrim($page['loc'], '/'));
            $xml .= $this->url($loc, now()->toDateString(), $page['changefreq'], $page['priority']);
        }

        return $this->xml($xml . $this->closeUrlset());
    }

    /** GET /sitemap-medex-brands.xml — brand pages from the shared JSON data. */
    public function medexBrands(): Response
    {
        try {
            $brands = app(MedicinesDataService::class)->getAllBrands();
        } catch (\Throwable $e) {
            Log::error('Sitemap MedEx brands error: ' . $e->getMessage());
            $brands = [];
        }

        $xml = $this->openUrlset();
        foreach ($brands as $brand) {
            $id = $brand['_id'] ?? null;
            if ($id === null) {
                continue;
            }
            $loc = url('/medicines/brand/' . (int) $id);
            $xml .= $this->url($loc, now()->toDateString(), 'monthly', 0.5);
        }

        return $this->xml($xml . $this->closeUrlset());
    }

    /** GET /sitemap-products.xml — 301 alias for legacy / marketing URLs. */
    public function productsRedirect(): Response
    {
        return redirect('/sitemap-services.xml', 301);
    }

    protected function xml(string $content): Response
    {
        return response($content, 200, [
            'Content-Type' => 'application/xml; charset=utf-8',
            'Cache-Control' => 'public, max-age=86400',
            'X-Robots-Tag' => 'noindex',
        ]);
    }

    protected function openUrlset(): string
    {
        return "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
            . "<urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">\n";
    }

    protected function closeUrlset(): string
    {
        return "</urlset>\n";
    }

    protected function url(string $loc, string $lastmod, string $changefreq, float $priority): string
    {
        return " <url>\n"
            . "  <loc>" . htmlspecialchars($loc, ENT_XML1 | ENT_QUOTES, 'UTF-8') . "</loc>\n"
            . "  <lastmod>{$lastmod}</lastmod>\n"
            . "  <changefreq>{$changefreq}</changefreq>\n"
            . "  <priority>" . rtrim(rtrim(number_format($priority, 1), '0'), '.') . "</priority>\n"
            . " </url>\n";
    }

    /**
     * Run a query defensively (same as legacy try/catch around each sitemap).
     */
    protected function safe(callable $fn): array
    {
        try {
            return $fn();
        } catch (\Throwable $e) {
            Log::error('Sitemap query error: ' . $e->getMessage());

            return [];
        }
    }
}